### ISSUE TITLE
Arpeggiate (Play each note one after the other)

### ISSUE THREAD

**Issue by nicoblabla** [amiguet/harpejjitabs#13]

**Comment by amiguet** [comment]
There's a small bug in this feature: notes should be played in the following order:
- strings from left to right
- on each string, from low to high.

Presently the first point is OK, but the second is reversed: on the same string, notes are played from high to low.

Also, I would prefer that notes are played a little slower (add some delay between each note). The present state works OK for chords, but is much too fast for scales.

**Comment by nicoblabla** [comment]
Is it still too fast ?
And is the order correct now ?

**Comment by amiguet** [comment]
> Is it still too fast ?

Yes, still a little bit for me. But already better :-)

> And is the order correct now ?

No. For instance, when arpeggiating the following file

[test_arpeggiate.htab.zip](https://github.com/amiguet/harpejjitabs/files/5500527/test_arpeggiate.htab.zip)

I'd expect to hear "C D E F G" and I hear "C D F E G" (F and E inverted).

BTW I like the new "highlight notes when played" feature :-)

**Comment by nicoblabla** [comment]
> I'd expect to hear "C D E F G" and I hear "C D F E G" (F and E inverted).
It seems to be a broswer issue maybe. I hear and see "C D E F G" being played

I will hopefully find a solution

**Comment by nicoblabla** [comment]
I'v changed the way it sort the notes, and now it seems to work well everywhere !

&nbsp;

First version, work correctly on Chrome and Safari, but not (linux) Firefox:
```js
let notes = this.playlist.sort((a, b) => (a.y > b.y) ? 1 : -1)
                    .sort((a, b) => (a.x > b.x) ? 1 : -1)
                    .map(a => a.note);
```

&nbsp;


Final version, work correctly on Chrome and Safari and Firefox:
```js
let notes = this.playlist.sort((a, b) => { return b.y - a.y })
                    .sort((a, b) => { return a.x - b.x })
                    .map(a => a.note);
```

Not really sure why tho

**Comment by amiguet** [comment]
I can confirm that the note order is now correct on FF :-)

The default 0.3 value sounds like a good timing for me. Another possible option, since it is already implemented, would be to change the text field into a nicer input and let the user chose the speed. Not sure what type of input would fit nicely into the side tray, though.

Small detail: when playing simultaneously, the notes nicely fade out, but when arpeggiating, the last note is cut out abruptly. Is it possible to let it fade out?
