### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by nicoblabla** [amiguet/harpejjitabs#27]
R: reframe
delete (when selecting marks): delete
P: play
M: mute/unmute
etc

**Comment by amiguet** [comment]
Great idea! :-)

**Comment by amiguet** [comment]
I like this feature! :-)

Now a few remarks to make it even better

1. Bug
    - When typing a title, the shortcuts should be deactivated. For example, in the present situation, typing a title with "r" inside is very confusing!
2. Enhancements
    - Include more shortcuts, like 
        - toggle note names (n)
        - toggle fret numbers (f)
        - play sequentially (shift-P? or s? or...)
        - is it possible to hijack the standard ctrl-s and ctrl-o to work as save and load?
        - not sure what shortcuts to have for both export buttons - and if it's even necessary
    - Document shortcuts inside the app: possible solution include
        - Underline the letter (e.g. underline *R* in *Reframe*). Of course this limits the possible shortcuts.
        - Add the shortcut after the action name: *Reframe (R)*, *Play sequentially (Shift-P)*
        - Add a help page documenting various things, including shortcuts.
