### ISSUE TITLE
Add link to githubpages in About Section, so everyone can try it

### ISSUE THREAD

**Issue by grunenwald** [amiguet/harpejjitabs#9]

**Comment by grunenwald** [comment]
@amiguet : apparemment tu es le seul à avoir le droit de faire ça... ;)

**Comment by amiguet** [comment]
Not sure what you mean by "About section". I added a link at the top of README.txt (commit ad20123). Please reopen if that wasn't what you meant.

**Comment by grunenwald** [comment]
<img width="673" alt="Capture d’écran 2020-10-26 à 16 18 42" src="https://user-images.githubusercontent.com/1151212/97191433-299c0480-17a7-11eb-92d2-9a150ed1cacd.png">

You should have a ⚙ right of the **About** line to edit the About section, with a field for the project's URL

**Comment by amiguet** [comment]
Oh, missed that, sorry. Thanks for clarifying! Done.
